import { withPayload } from "@payloadcms/next/withPayload";
import { NextConfig } from "next";

/** @type {import('next').NextConfig} */
const nextConfig: NextConfig = {
  experimental: {
    reactCompiler: false,
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          {
            key: "X-Frame-Options",
            value: "DENY",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
        ],
      },
    ];
  },
  async rewrites() {
    return [
      /**
       * PT-BR Pages
       */
      { source: "/", destination: "/index.html" },
      { source: "/business-lounge", destination: "/business-lounge/index.html" },
      { source: "/como-chegar", destination: "/como-chegar/index.html" },
      { source: "/contato", destination: "/contato/index.html" },
      { source: "/expositores", destination: "/expositores/index.html" },
      { source: "/imprensa", destination: "/imprensa/index.html" },
      { source: "/palestras", destination: "/palestras/index.html" },
      { source: "/seja-um-expositor", destination: "/seja-um-expositor/index.html" },
      { source: "/sobre-o-evento", destination: "/sobre-o-evento/index.html" },

      /**
       * EN Pages
       */
      { source: "/en", destination: "/en/index.html" },
      { source: "/en/about", destination: "/en/about/index.html" },
      { source: "/en/be-an-exhibitor", destination: "/en/be-an-exhibitor/index.html" },
      { source: "/en/business-lounge", destination: "/en/business-lounge/index.html" },
      { source: "/en/contact", destination: "/en/contact/index.html" },
      { source: "/en/exhibitors", destination: "/en/exhibitors/index.html" },
      { source: "/en/lectures", destination: "/en/lectures/index.html" },
      { source: "/en/venue-directions", destination: "/en/venue-directions/index.html" },

      /**
       * Notícias
       */
      { source: "/noticias", destination: "/noticias/index.html" },
      { source: "/noticias/2a-edicao-novos-designers-brasil", destination: "/noticias/2a-edicao-novos-designers-brasil/index.html" },
      { source: "/noticias/2o-dia-da-feira-promove-networking-e-atualizacao-profissional", destination: "/noticias/2o-dia-da-feira-promove-networking-e-atualizacao-profissional/index.html" },
      { source: "/noticias/2o-dia-da-gotex-show-2017-foco-em-tendencias-e-no-profissional-textil", destination: "/noticias/2o-dia-da-gotex-show-2017-foco-em-tendencias-e-no-profissional-textil/index.html" },
      { source: "/noticias/32-jovens-designers-aderem-ao-novos-designers-brasil", destination: "/noticias/32-jovens-designers-aderem-ao-novos-designers-brasil/index.html" },
      { source: "/noticias/7a-gotex-show-comecou-hoje-a-semana-de-encontros-e-negocios-do-setor-textil", destination: "/noticias/7a-gotex-show-comecou-hoje-a-semana-de-encontros-e-negocios-do-setor-textil/index.html" },
      { source: "/noticias/a-gotex-show-oferece-em-sua-8a-edicao-oportunidades-para-empresas", destination: "/noticias/a-gotex-show-oferece-em-sua-8a-edicao-oportunidades-para-empresas/index.html" },
      { source: "/noticias/abcomm-faz-parceria-com-a-gotex-show-2017", destination: "/noticias/abcomm-faz-parceria-com-a-gotex-show-2017/index.html" },
      { source: "/noticias/aciju-e-gotex-show-parceria-em-prol-do-mercado-nacional-de-lingerie", destination: "/noticias/aciju-e-gotex-show-parceria-em-prol-do-mercado-nacional-de-lingerie/index.html" },
      { source: "/noticias/acompanhe-os-ganhadores-do-concurso-novos-designers-brasil-e-apple-watch", destination: "/noticias/acompanhe-os-ganhadores-do-concurso-novos-designers-brasil-e-apple-watch/index.html" },
      { source: "/noticias/alexandre-herchcovitch-e-fashion-snoops-sao-destaques-na-programacao-da-gotex-2019", destination: "/noticias/alexandre-herchcovitch-e-fashion-snoops-sao-destaques-na-programacao-da-gotex-2019/index.html" },
      { source: "/noticias/alexandre-herchcovitch-participa-de-forum-de-sustentabilidade", destination: "/noticias/alexandre-herchcovitch-participa-de-forum-de-sustentabilidade/index.html" },
      { source: "/noticias/bolivia-participa-com-25-empresas-da-gotex-show", destination: "/noticias/bolivia-participa-com-25-empresas-da-gotex-show/index.html" },
      { source: "/noticias/brasil-2020-perspectivas-para-o-proximo-ano", destination: "/noticias/brasil-2020-perspectivas-para-o-proximo-ano/index.html" },
      { source: "/noticias/brasil-e-china-parceria-de-cooperacao", destination: "/noticias/brasil-e-china-parceria-de-cooperacao/index.html" },
      { source: "/noticias/bressan-confirma-participacao-na-gotex-show", destination: "/noticias/bressan-confirma-participacao-na-gotex-show/index.html" },
      { source: "/noticias/bressan-underwear-confirma-presenca-na-gotex-show", destination: "/noticias/bressan-underwear-confirma-presenca-na-gotex-show/index.html" },
      { source: "/noticias/camara-mexico-brasil-presente-na-gotex-show-2018", destination: "/noticias/camara-mexico-brasil-presente-na-gotex-show-2018/index.html" },
      { source: "/noticias/camila-toledo-diretora-do-fashion-snoops-brasil-na-gotex-show-2017", destination: "/noticias/camila-toledo-diretora-do-fashion-snoops-brasil-na-gotex-show-2017/index.html" },
      { source: "/noticias/camila-toledo-diretora-fashion-snoops-brasil-futuro-moda-varejo", destination: "/noticias/camila-toledo-diretora-fashion-snoops-brasil-futuro-moda-varejo/index.html" },
      { source: "/noticias/camila-toledo-do-fashion-snoops-fala-sobre-tendencias-moda-casa-na-gotex-show", destination: "/noticias/camila-toledo-do-fashion-snoops-fala-sobre-tendencias-moda-casa-na-gotex-show/index.html" },
      { source: "/noticias/comecou-a-5a-edicao-da-gotex-show-os-melhores-momentos-do-primeiro-dia-da-feira-internacional-de-produtos-texteis", destination: "/noticias/comecou-a-5a-edicao-da-gotex-show-os-melhores-momentos-do-primeiro-dia-da-feira-internacional-de-produtos-texteis/index.html" },
      { source: "/noticias/comercio-global-competitividade-e-a-chave-do-sucesso", destination: "/noticias/comercio-global-competitividade-e-a-chave-do-sucesso/index.html" },
      { source: "/noticias/comercio-global-ganha-novas-perspectivas", destination: "/noticias/comercio-global-ganha-novas-perspectivas/index.html" },
      { source: "/noticias/concurso-apresenta-colecoes-na-segunda-2710", destination: "/noticias/concurso-apresenta-colecoes-na-segunda-2710/index.html" },
      { source: "/noticias/concurso-novos-designers-brasil-chega-a-etapa-final", destination: "/noticias/concurso-novos-designers-brasil-chega-a-etapa-final/index.html" },
      { source: "/noticias/concurso-novos-designers-brasil-chega-a-reta-final", destination: "/noticias/concurso-novos-designers-brasil-chega-a-reta-final/index.html" },
      { source: "/noticias/confeccoes-peruanas-na-gotex-show-2017", destination: "/noticias/confeccoes-peruanas-na-gotex-show-2017/index.html" },
      { source: "/noticias/confira-as-principais-tendencias-inovacoes-e-produtos-em-destaque-da-gotex-show-2019", destination: "/noticias/confira-as-principais-tendencias-inovacoes-e-produtos-em-destaque-da-gotex-show-2019/index.html" },
      { source: "/noticias/confira-bate-papo-especialitas-rumos-comercial-internacional", destination: "/noticias/confira-bate-papo-especialitas-rumos-comercial-internacional/index.html" },
      { source: "/noticias/confirmada-a-programacao-de-eventos-paralelos-da-feira-gotex-show", destination: "/noticias/confirmada-a-programacao-de-eventos-paralelos-da-feira-gotex-show/index.html" },
      { source: "/noticias/conheca-os-finalistas-do-concurso-novos-designers-brasil-2016", destination: "/noticias/conheca-os-finalistas-do-concurso-novos-designers-brasil-2016/index.html" },
      { source: "/noticias/consul-da-india-em-sao-paulo-visita-a-gotex-show", destination: "/noticias/consul-da-india-em-sao-paulo-visita-a-gotex-show/index.html" },
      { source: "/noticias/consultoria-em-negocios-internacionais", destination: "/noticias/consultoria-em-negocios-internacionais/index.html" },
      { source: "/noticias/consultoria-especializada-para-pme", destination: "/noticias/consultoria-especializada-para-pme/index.html" },
      { source: "/noticias/depoimentos-expositores-e-visitantes", destination: "/noticias/depoimentos-expositores-e-visitantes/index.html" },
      { source: "/noticias/diario-de-viagem-vencedor-do-concurso-novos-designers-brasil-retorna-da-china-e-mostra-suas-percepcoes-referencias-e-inspiracoes-que-teve-sobre-a-moda-no-pais", destination: "/noticias/diario-de-viagem-vencedor-do-concurso-novos-designers-brasil-retorna-da-china-e-mostra-suas-percepcoes-referencias-e-inspiracoes-que-teve-sobre-a-moda-no-pais/index.html" },
      { source: "/noticias/divulgacao-da-gotex-show-2013", destination: "/noticias/divulgacao-da-gotex-show-2013/index.html" },
      { source: "/noticias/e-commerce-no-mercado-textil", destination: "/noticias/e-commerce-no-mercado-textil/index.html" },
      { source: "/noticias/empresa-de-modelagem-se-apresenta-pela-primeira-vez-na-gotex-show", destination: "/noticias/empresa-de-modelagem-se-apresenta-pela-primeira-vez-na-gotex-show/index.html" },
      { source: "/noticias/empresa-paquistanesa-reafirma-interesse-em-parceria-no-mercado-brasileiro", destination: "/noticias/empresa-paquistanesa-reafirma-interesse-em-parceria-no-mercado-brasileiro/index.html" },
      { source: "/noticias/empresa-traz-tecnologia-dope-dyed-para-a-gotex-show", destination: "/noticias/empresa-traz-tecnologia-dope-dyed-para-a-gotex-show/index.html" },
      { source: "/noticias/empresas-brasileiras-confirmam-participacao-na-go-tex-show-2014", destination: "/noticias/empresas-brasileiras-confirmam-participacao-na-go-tex-show-2014/index.html" },
      { source: "/noticias/empresas-brasileiras-do-setor-textil-buscam-novas-oportunidades-no-mercado-global-na-gotex-show-2016", destination: "/noticias/empresas-brasileiras-do-setor-textil-buscam-novas-oportunidades-no-mercado-global-na-gotex-show-2016/index.html" },
      { source: "/noticias/empresas-brasileiras-marcam-presenca-na-gotex-show-2015", destination: "/noticias/empresas-brasileiras-marcam-presenca-na-gotex-show-2015/index.html" },
      { source: "/noticias/encontro-produtos-inovadores", destination: "/noticias/encontro-produtos-inovadores/index.html" },
      { source: "/noticias/encontro-textil-traz-novidades-para-cadeia-produtiva-do-jeans", destination: "/noticias/encontro-textil-traz-novidades-para-cadeia-produtiva-do-jeans/index.html" },
      { source: "/noticias/entidades-texteis-confirmam-apoio-a-go-tex-show-2013", destination: "/noticias/entidades-texteis-confirmam-apoio-a-go-tex-show-2013/index.html" },
      { source: "/noticias/entrevista-jessica-jin", destination: "/noticias/entrevista-jessica-jin/index.html" },
      { source: "/noticias/entrevista-pan-faming", destination: "/noticias/entrevista-pan-faming/index.html" },
      { source: "/noticias/especialistas-em-moda-falam-sobre-o-verao-2020-e-tendencias-em-tecido", destination: "/noticias/especialistas-em-moda-falam-sobre-o-verao-2020-e-tendencias-em-tecido/index.html" },
      { source: "/noticias/esta-aberta-a-3a-edicao-da-gotex-show-feira-se-consolida-como-global-sourcing-para-o-setor-textil", destination: "/noticias/esta-aberta-a-3a-edicao-da-gotex-show-feira-se-consolida-como-global-sourcing-para-o-setor-textil/index.html" },
      { source: "/noticias/esta-aberta-a-gotex-show-2016", destination: "/noticias/esta-aberta-a-gotex-show-2016/index.html" },
      { source: "/noticias/esta-aberta-a-gotex-show-2019", destination: "/noticias/esta-aberta-a-gotex-show-2019/index.html" },
      { source: "/noticias/estao-abertas-as-pre-inscricoes-do-concurso-novos-designers-brasil-2016", destination: "/noticias/estao-abertas-as-pre-inscricoes-do-concurso-novos-designers-brasil-2016/index.html" },
      { source: "/noticias/evento-oficial-de-lancamento-da-feira-gotex-show", destination: "/noticias/evento-oficial-de-lancamento-da-feira-gotex-show/index.html" },
      { source: "/noticias/eventos-que-geram-negocio-e-desenvolvem-a-economia-de-diversos-setores", destination: "/noticias/eventos-que-geram-negocio-e-desenvolvem-a-economia-de-diversos-setores/index.html" },
      { source: "/noticias/expectativas-e-novos-negocios", destination: "/noticias/expectativas-e-novos-negocios/index.html" },
      { source: "/noticias/expectativas-sao-positivas-para-o-setor-de-cama-mesa-e-banho", destination: "/noticias/expectativas-sao-positivas-para-o-setor-de-cama-mesa-e-banho/index.html" },
      { source: "/noticias/expositores-da-go-tex-show-ja-realizam-negocios-com-empresas-brasileiras", destination: "/noticias/expositores-da-go-tex-show-ja-realizam-negocios-com-empresas-brasileiras/index.html" },
      { source: "/noticias/fashion-snoops-preview-verao-19", destination: "/noticias/fashion-snoops-preview-verao-19/index.html" },
      { source: "/noticias/fcem-sera-representada-na-shanghaitex-2013", destination: "/noticias/fcem-sera-representada-na-shanghaitex-2013/index.html" },
      { source: "/noticias/feira-traz-inovacao-em-fibras-e-tecidos", destination: "/noticias/feira-traz-inovacao-em-fibras-e-tecidos/index.html" },
      { source: "/noticias/feira-voltada-ao-mercado-textil-reune-principais-players-mundiais-do-setor", destination: "/noticias/feira-voltada-ao-mercado-textil-reune-principais-players-mundiais-do-setor/index.html" },
      { source: "/noticias/fernanda-garcia-vence-a-3a-edicao-do-concurso-novos-designers-brasil", destination: "/noticias/fernanda-garcia-vence-a-3a-edicao-do-concurso-novos-designers-brasil/index.html" },
      { source: "/noticias/fibra-de-isolamento-termico-feita-de-garrafas-pet-e-alternativa-sustentavel-para-o-vestuario-de-frio", destination: "/noticias/fibra-de-isolamento-termico-feita-de-garrafas-pet-e-alternativa-sustentavel-para-o-vestuario-de-frio/index.html" },
      { source: "/noticias/francesco-bogarin-e-o-vencedor-da-2a-edicao-do-novos-designers-brasil", destination: "/noticias/francesco-bogarin-e-o-vencedor-da-2a-edicao-do-novos-designers-brasil/index.html" },
      { source: "/noticias/fujian-changle-destaca-se-com-portfolio-de-rendas-tecidos-de-malha-e-estampados", destination: "/noticias/fujian-changle-destaca-se-com-portfolio-de-rendas-tecidos-de-malha-e-estampados/index.html" },
      { source: "/noticias/go-tex-show-2013-ja-tem-100-dos-stands-comercializados", destination: "/noticias/go-tex-show-2013-ja-tem-100-dos-stands-comercializados/index.html" },
      { source: "/noticias/go-tex-show-2013-vai-oferecer-transfer-gratuito", destination: "/noticias/go-tex-show-2013-vai-oferecer-transfer-gratuito/index.html" },
      { source: "/noticias/go-tex-show-2014-apresenta-primeira-edicao-do-concurso-novos-designers-brasil", destination: "/noticias/go-tex-show-2014-apresenta-primeira-edicao-do-concurso-novos-designers-brasil/index.html" },
      { source: "/noticias/go-tex-show-2014-de-casa-nova", destination: "/noticias/go-tex-show-2014-de-casa-nova/index.html" },
      { source: "/noticias/go-tex-show-2014-ja-conta-com-significativa-reserva-de-stands", destination: "/noticias/go-tex-show-2014-ja-conta-com-significativa-reserva-de-stands/index.html" },
      { source: "/noticias/go-tex-show-2014-se-firma-como-feira-global", destination: "/noticias/go-tex-show-2014-se-firma-como-feira-global/index.html" },
      { source: "/noticias/go-tex-show-e-aberta-em-sao-paulo-promovendo-o-intercambio-entre-empresas-brasileiras-e-chinesas", destination: "/noticias/go-tex-show-e-aberta-em-sao-paulo-promovendo-o-intercambio-entre-empresas-brasileiras-e-chinesas/index.html" },
      { source: "/noticias/go-tex-show-sorteia-ipads-para-visitantes", destination: "/noticias/go-tex-show-sorteia-ipads-para-visitantes/index.html" },
      { source: "/noticias/gotex_show_2023_aberta_ao_publico", destination: "/noticias/gotex_show_2023_aberta_ao_publico/index.html" },
      { source: "/noticias/gotex_show_abre_debate_sobre_o_futuro_da_moda-", destination: "/noticias/gotex_show_abre_debate_sobre_o_futuro_da_moda-/index.html" },
      { source: "/noticias/gotex-2019", destination: "/noticias/gotex-2019/index.html" },
      { source: "/noticias/gotex-evento-2023", destination: "/noticias/gotex-evento-2023/index.html" },
      { source: "/noticias/gotex-participa-de-missao-ao-paraguai", destination: "/noticias/gotex-participa-de-missao-ao-paraguai/index.html" },
      { source: "/noticias/gotex-sedia-rodada-de-negocios-para-o-setor-textil-no-dia-10-de-setembro", destination: "/noticias/gotex-sedia-rodada-de-negocios-para-o-setor-textil-no-dia-10-de-setembro/index.html" },
      { source: "/noticias/gotex-show-2013-feira-de-materia-prima-chinesa-premium-ja-tem-90-dos-stands-comercializa", destination: "/noticias/gotex-show-2013-feira-de-materia-prima-chinesa-premium-ja-tem-90-dos-stands-comercializa/index.html" },
      { source: "/noticias/gotex-show-2013", destination: "/noticias/gotex-show-2013/index.html" },
      { source: "/noticias/gotex-show-2015-abre-inscricoes", destination: "/noticias/gotex-show-2015-abre-inscricoes/index.html" },
      { source: "/noticias/gotex-show-2016-esta-aberta-a-maior-plataforma-internacional-textil-do-pais", destination: "/noticias/gotex-show-2016-esta-aberta-a-maior-plataforma-internacional-textil-do-pais/index.html" },
      { source: "/noticias/gotex-show-2016-feira-promoveu-negocios-e-networking-profissional", destination: "/noticias/gotex-show-2016-feira-promoveu-negocios-e-networking-profissional/index.html" },
      { source: "/noticias/gotex-show-2016-promove-ciclo-de-palestras-para-empresarios-do-setor-textil", destination: "/noticias/gotex-show-2016-promove-ciclo-de-palestras-para-empresarios-do-setor-textil/index.html" },
      { source: "/noticias/gotex-show-2016-resultados-da-feira", destination: "/noticias/gotex-show-2016-resultados-da-feira/index.html" },
      { source: "/noticias/gotex-show-2017-cama-mesa-e-banho", destination: "/noticias/gotex-show-2017-cama-mesa-e-banho/index.html" },
      { source: "/noticias/gotex-show-2017-celebra-cinco-edicoes", destination: "/noticias/gotex-show-2017-celebra-cinco-edicoes/index.html" },
      { source: "/noticias/gotex-show-2017-destaques-em-produtos", destination: "/noticias/gotex-show-2017-destaques-em-produtos/index.html" },
      { source: "/noticias/gotex-show-2017-dia-01-aprimoramento-para-confeccionistas", destination: "/noticias/gotex-show-2017-dia-01-aprimoramento-para-confeccionistas/index.html" },
      { source: "/noticias/gotex-show-2018-e-inaugurada", destination: "/noticias/gotex-show-2018-e-inaugurada/index.html" },
      { source: "/noticias/gotex-show-2019-chega-para-fomentar-novas-oportunidades", destination: "/noticias/gotex-show-2019-chega-para-fomentar-novas-oportunidades/index.html" },
      { source: "/noticias/gotex-show-2022-encontro-internacional-textil-de-moda-e-negocios", destination: "/noticias/gotex-show-2022-encontro-internacional-textil-de-moda-e-negocios/index.html" },
      { source: "/noticias/gotex-show-2022-encontro-textil-reune-mais-de-70-expositores", destination: "/noticias/gotex-show-2022-encontro-textil-reune-mais-de-70-expositores/index.html" },
      { source: "/noticias/gotex-show-2022-ja-comecou-gerar-oportunidades-de-negocios-para-empresarios-do-brasil", destination: "/noticias/gotex-show-2022-ja-comecou-gerar-oportunidades-de-negocios-para-empresarios-do-brasil/index.html" },
      { source: "/noticias/gotex-show-celebra-5-edicoes-em-2017", destination: "/noticias/gotex-show-celebra-5-edicoes-em-2017/index.html" },
      { source: "/noticias/gotex-show-chega-a-4a-edicao", destination: "/noticias/gotex-show-chega-a-4a-edicao/index.html" },
      { source: "/noticias/gotex-show-comunicado-ao-mercado", destination: "/noticias/gotex-show-comunicado-ao-mercado/index.html" },
      { source: "/noticias/gotex-show-conclui-sua-8-edicao", destination: "/noticias/gotex-show-conclui-sua-8-edicao/index.html" },
      { source: "/noticias/gotex-show-edicao-de-2023-e-encerrada-com-sucesso-promovendo-oportunidades-na-cadeia-textil", destination: "/noticias/gotex-show-edicao-de-2023-e-encerrada-com-sucesso-promovendo-oportunidades-na-cadeia-textil/index.html" },
      { source: "/noticias/gotex-show-esta-de-casa-nova", destination: "/noticias/gotex-show-esta-de-casa-nova/index.html" },
      { source: "/noticias/gotex-show-ja-conta-com-95-dos-espacos-comercializados", destination: "/noticias/gotex-show-ja-conta-com-95-dos-espacos-comercializados/index.html" },
      { source: "/noticias/gotex-show-realiza-evento-em-rondonia-sobre-oportunidades-internacionais-no-mercado-textil", destination: "/noticias/gotex-show-realiza-evento-em-rondonia-sobre-oportunidades-internacionais-no-mercado-textil/index.html" },
      { source: "/noticias/gotex-show-realiza-road-show-internacional", destination: "/noticias/gotex-show-realiza-road-show-internacional/index.html" },
      { source: "/noticias/gotex-show-traz-novidades-para-o-setor-textil", destination: "/noticias/gotex-show-traz-novidades-para-o-setor-textil/index.html" },
      { source: "/noticias/gotex-show-traz-programacao-de-palestras-com-foco-no-comercio-eletronico-e-na-exposicao-das-marcas-no-meio-digital", destination: "/noticias/gotex-show-traz-programacao-de-palestras-com-foco-no-comercio-eletronico-e-na-exposicao-das-marcas-no-meio-digital/index.html" },
      { source: "/noticias/gotex-show-traz-selecao-exclusiva-de-estamparia-algodao-pima-toalhas-e-meias", destination: "/noticias/gotex-show-traz-selecao-exclusiva-de-estamparia-algodao-pima-toalhas-e-meias/index.html" },
      { source: "/noticias/ha-cinco-anos-no-mercado-nacional-feira-traz-diversidade-e-inovacao-para-o-setor-textil", destination: "/noticias/ha-cinco-anos-no-mercado-nacional-feira-traz-diversidade-e-inovacao-para-o-setor-textil/index.html" },
      { source: "/noticias/henrique-reis-relacoes-internacionais-da-gotex-fala-sobre-as-novidades-do-evento-para-2019-sustentabilidade-e-a-globalizacao-no-setor-textil", destination: "/noticias/henrique-reis-relacoes-internacionais-da-gotex-fala-sobre-as-novidades-do-evento-para-2019-sustentabilidade-e-a-globalizacao-no-setor-textil/index.html" },
      { source: "/noticias/india-traz-fios-aviamentos-bordados-e-vestuario-para-a-gotex", destination: "/noticias/india-traz-fios-aviamentos-bordados-e-vestuario-para-a-gotex/index.html" },
      { source: "/noticias/industria-textil-nacional-expectativa-de-recuperacao-para-2020", destination: "/noticias/industria-textil-nacional-expectativa-de-recuperacao-para-2020/index.html" },
      { source: "/noticias/inovacao-e-tecnologia-made-in-italy-na-gotex-show", destination: "/noticias/inovacao-e-tecnologia-made-in-italy-na-gotex-show/index.html" },
      { source: "/noticias/inscricoes-abertas-para-a-6a-gotex-show", destination: "/noticias/inscricoes-abertas-para-a-6a-gotex-show/index.html" },
      { source: "/noticias/internacionalizacao-e-intercambio-na-cadeia-textil-marcam-a-3a-edicao-da-gotex-show", destination: "/noticias/internacionalizacao-e-intercambio-na-cadeia-textil-marcam-a-3a-edicao-da-gotex-show/index.html" },
      { source: "/noticias/jessica-jin-vence-o-concurso-novos-designers-brasil", destination: "/noticias/jessica-jin-vence-o-concurso-novos-designers-brasil/index.html" },
      { source: "/noticias/lancamento-da-segunda-edicao-da-gotex-show", destination: "/noticias/lancamento-da-segunda-edicao-da-gotex-show/index.html" },
      { source: "/noticias/macro-tendencias-verao-2025-inverno-2024", destination: "/noticias/macro-tendencias-verao-2025-inverno-2024/index.html" },
      { source: "/noticias/macrotendencias-verao-2020-e-tendencias-em-tecidos-foram-temas-no-segundo-dia-da-gotex-show", destination: "/noticias/macrotendencias-verao-2020-e-tendencias-em-tecidos-foram-temas-no-segundo-dia-da-gotex-show/index.html" },
      { source: "/noticias/marketing-digital-para-vestuario", destination: "/noticias/marketing-digital-para-vestuario/index.html" },
      { source: "/noticias/marketing-digital-processo-produtivo-e-e-commerce-sao-temas-de-palestras-gratuitas-na-gotex-show", destination: "/noticias/marketing-digital-processo-produtivo-e-e-commerce-sao-temas-de-palestras-gratuitas-na-gotex-show/index.html" },
      { source: "/noticias/medidas-para-minimizar-o-impacto-do-covid-19", destination: "/noticias/medidas-para-minimizar-o-impacto-do-covid-19/index.html" },
      { source: "/noticias/micro-e-pequenas-empresas-na-gotex-show", destination: "/noticias/micro-e-pequenas-empresas-na-gotex-show/index.html" },
      { source: "/noticias/moda-casa-e-destaque-no-3o-dia-da-gotex-show", destination: "/noticias/moda-casa-e-destaque-no-3o-dia-da-gotex-show/index.html" },
      { source: "/noticias/moda-feminina-moda-casa-e-tecidos-sao-temas-de-palestras-na-gotex", destination: "/noticias/moda-feminina-moda-casa-e-tecidos-sao-temas-de-palestras-na-gotex/index.html" },
      { source: "/noticias/modacrea-retorna-a-gotexshow", destination: "/noticias/modacrea-retorna-a-gotexshow/index.html" },
      { source: "/noticias/modacrea-traz-amplo-portfolio-de-tecidos-para-o-mercado-nacional", destination: "/noticias/modacrea-traz-amplo-portfolio-de-tecidos-para-o-mercado-nacional/index.html" },
      { source: "/noticias/mostras-simultaneas-enriquecem-a-visitacao-do-publico-e-expositores", destination: "/noticias/mostras-simultaneas-enriquecem-a-visitacao-do-publico-e-expositores/index.html" },
      { source: "/noticias/nanovetores-nanotecnologia-textil-na-gotex-show-2016", destination: "/noticias/nanovetores-nanotecnologia-textil-na-gotex-show-2016/index.html" },
      { source: "/noticias/negociacoes-marcam-o-segundo-dia-gotex-show", destination: "/noticias/negociacoes-marcam-o-segundo-dia-gotex-show/index.html" },
      { source: "/noticias/negocios-e-exportacoes-sao-destaque-no-2o-dia-da-gotex-show-2016", destination: "/noticias/negocios-e-exportacoes-sao-destaque-no-2o-dia-da-gotex-show-2016/index.html" },
      { source: "/noticias/negocios-e-sustentabilidade-marcam-segundo-dia-da-gotex", destination: "/noticias/negocios-e-sustentabilidade-marcam-segundo-dia-da-gotex/index.html" },
      { source: "/noticias/negocios-em-pauta", destination: "/noticias/negocios-em-pauta/index.html" },
      { source: "/noticias/novidades-dos-expositores", destination: "/noticias/novidades-dos-expositores/index.html" },
      { source: "/noticias/novidades-e-lancamentos-para-o-segmento-homewear-cama-mesa-e-banho", destination: "/noticias/novidades-e-lancamentos-para-o-segmento-homewear-cama-mesa-e-banho/index.html" },
      { source: "/noticias/novidades-mercado-textil-encontro-setembro", destination: "/noticias/novidades-mercado-textil-encontro-setembro/index.html" },
      { source: "/noticias/novo-morar-lares-funcionais-aconchegantes-tendencia-moda-casa", destination: "/noticias/novo-morar-lares-funcionais-aconchegantes-tendencia-moda-casa/index.html" },
      { source: "/noticias/novos-designers-brasil-2016-bate-recorde-de-inscricoes", destination: "/noticias/novos-designers-brasil-2016-bate-recorde-de-inscricoes/index.html" },
      { source: "/noticias/novos-designers-brasil-divulga-finalistas", destination: "/noticias/novos-designers-brasil-divulga-finalistas/index.html" },
      { source: "/noticias/novos-designers-brasil-faz-sua-estreia-estadual", destination: "/noticias/novos-designers-brasil-faz-sua-estreia-estadual/index.html" },
      { source: "/noticias/novos-designers-brasil-supera-expectativas-de-inscricoes", destination: "/noticias/novos-designers-brasil-supera-expectativas-de-inscricoes/index.html" },
      { source: "/noticias/o-futuro-da-sustentabilidade-na-industria-da-moda", destination: "/noticias/o-futuro-da-sustentabilidade-na-industria-da-moda/index.html" },
      { source: "/noticias/o-futuro-e-a-sustentabilidade", destination: "/noticias/o-futuro-e-a-sustentabilidade/index.html" },
      { source: "/noticias/o-melhor-da-producao-mundial-textil-na-6a-edicao-da-gotex-show", destination: "/noticias/o-melhor-da-producao-mundial-textil-na-6a-edicao-da-gotex-show/index.html" },
      { source: "/noticias/ontem-aconteceu-abertura-da-8-edicao-gotex-show", destination: "/noticias/ontem-aconteceu-abertura-da-8-edicao-gotex-show/index.html" },
      { source: "/noticias/oportunidades-no-mercado-nacional-de-vestuario", destination: "/noticias/oportunidades-no-mercado-nacional-de-vestuario/index.html" },
      { source: "/noticias/organizacao-do-novos-designers-brasil-divulga-finalistas", destination: "/noticias/organizacao-do-novos-designers-brasil-divulga-finalistas/index.html" },
      { source: "/noticias/organizacao-que-conecta-mulheres-empresarias-firma-parceria-com-a-gotex", destination: "/noticias/organizacao-que-conecta-mulheres-empresarias-firma-parceria-com-a-gotex/index.html" },
      { source: "/noticias/organizadores-da-go-tex-show-firmam-parceria-com-a-alobras", destination: "/noticias/organizadores-da-go-tex-show-firmam-parceria-com-a-alobras/index.html" },
      { source: "/noticias/palestra-da-go-tex-show-aborda-o-mercado-textil-chines", destination: "/noticias/palestra-da-go-tex-show-aborda-o-mercado-textil-chines/index.html" },
      { source: "/noticias/palestras-sobre-os-processos-para-a-exportacao-de-produtos-na-go-tex-show", destination: "/noticias/palestras-sobre-os-processos-para-a-exportacao-de-produtos-na-go-tex-show/index.html" },
      { source: "/noticias/parceria-gotex-show-e-feiras-congressos-e-renovada-para-2018", destination: "/noticias/parceria-gotex-show-e-feiras-congressos-e-renovada-para-2018/index.html" },
      { source: "/noticias/pavilhao-do-paquistao-traz-produtos-de-destaque-do-pais-para-feira-textil", destination: "/noticias/pavilhao-do-paquistao-traz-produtos-de-destaque-do-pais-para-feira-textil/index.html" },
      { source: "/noticias/peru-se-apresenta-na-gotex-show-16-e-traz-para-a-feira-a-excelencia-e-a-variedade-do-algodao-peruano", destination: "/noticias/peru-se-apresenta-na-gotex-show-16-e-traz-para-a-feira-a-excelencia-e-a-variedade-do-algodao-peruano/index.html" },
      { source: "/noticias/polo-de-lingerie-brasileiro", destination: "/noticias/polo-de-lingerie-brasileiro/index.html" },
      { source: "/noticias/presidente-do-ibrei-mauricio-prazak-fala-sobre-perspectivas-do-mercado-e-a-parceria-com-a-gotex-show", destination: "/noticias/presidente-do-ibrei-mauricio-prazak-fala-sobre-perspectivas-do-mercado-e-a-parceria-com-a-gotex-show/index.html" },
      { source: "/noticias/produtos-inovadores-sao-destaque-na-gotex-show-2016", destination: "/noticias/produtos-inovadores-sao-destaque-na-gotex-show-2016/index.html" },
      { source: "/noticias/programacao-seminario-go-tex-show-2014", destination: "/noticias/programacao-seminario-go-tex-show-2014/index.html" },
      { source: "/noticias/reinvencao-textil-como-industrias-do-setor-estao-se-mobilizando-para-produzir-epis-e-outros-itens-de-protecao", destination: "/noticias/reinvencao-textil-como-industrias-do-setor-estao-se-mobilizando-para-produzir-epis-e-outros-itens-de-protecao/index.html" },
      { source: "/noticias/rodada-de-negocios-ampliam-oportunidades-no-mercado-textil", destination: "/noticias/rodada-de-negocios-ampliam-oportunidades-no-mercado-textil/index.html" },
      { source: "/noticias/sao-paulo-recebe-feira-do-setor-textil-em-setembro", destination: "/noticias/sao-paulo-recebe-feira-do-setor-textil-em-setembro/index.html" },
      { source: "/noticias/sebrae-sp-leva-orientacao-para-micro-e-pequenas-empresas", destination: "/noticias/sebrae-sp-leva-orientacao-para-micro-e-pequenas-empresas/index.html" },
      { source: "/noticias/segmento-casa-e-destaque-em-feira-textil", destination: "/noticias/segmento-casa-e-destaque-em-feira-textil/index.html" },
      { source: "/noticias/segundo-dia-da-gotex-show-tem-foco-na-atualizacao-profissional-com-palestras-do-sebrae-sp-e-belas-artes", destination: "/noticias/segundo-dia-da-gotex-show-tem-foco-na-atualizacao-profissional-com-palestras-do-sebrae-sp-e-belas-artes/index.html" },
      { source: "/noticias/seminario-de-macrotendencias-marca-lancamento-da-7a-edicao-da-gotex-show", destination: "/noticias/seminario-de-macrotendencias-marca-lancamento-da-7a-edicao-da-gotex-show/index.html" },
      { source: "/noticias/seminario-ecotece-e-destaque-da-programacao-paralela-da-gotex-show-2013", destination: "/noticias/seminario-ecotece-e-destaque-da-programacao-paralela-da-gotex-show-2013/index.html" },
      { source: "/noticias/servicos-e-facilidades-promovem-o-intercambio-comercial-durante-a-gotex-show", destination: "/noticias/servicos-e-facilidades-promovem-o-intercambio-comercial-durante-a-gotex-show/index.html" },
      { source: "/noticias/setor-de-moda-casa-cresce-na-gotex-show", destination: "/noticias/setor-de-moda-casa-cresce-na-gotex-show/index.html" },
      { source: "/noticias/setor-textil-analises-e-perspectivas", destination: "/noticias/setor-textil-analises-e-perspectivas/index.html" },
      { source: "/noticias/setor-textil-espera-leve-recuperacao-apos-eleicoes", destination: "/noticias/setor-textil-espera-leve-recuperacao-apos-eleicoes/index.html" },
      { source: "/noticias/setor-textil-recebe-plataforma-de-eventos-para-a-cadeia-em-setembro-na-cidade-de-sao-paulo", destination: "/noticias/setor-textil-recebe-plataforma-de-eventos-para-a-cadeia-em-setembro-na-cidade-de-sao-paulo/index.html" },
      { source: "/noticias/shangtex-potencia-mundial-do-mercado-textil-expoe-na-gotex-show-2016", destination: "/noticias/shangtex-potencia-mundial-do-mercado-textil-expoe-na-gotex-show-2016/index.html" },
      { source: "/noticias/sorteio-de-apple-watch-aos-visitantes", destination: "/noticias/sorteio-de-apple-watch-aos-visitantes/index.html" },
      { source: "/noticias/sustentabilidade-desafio-industria-textil", destination: "/noticias/sustentabilidade-desafio-industria-textil/index.html" },
      { source: "/noticias/tendencias-de-moda-feminina-inverno-2018-e-preview-verao-2019-sob-a-otica-de-experts-em-moda", destination: "/noticias/tendencias-de-moda-feminina-inverno-2018-e-preview-verao-2019-sob-a-otica-de-experts-em-moda/index.html" },
      { source: "/noticias/tendencias-inverno-19-e-design-para-estamparia-sao-temas-de-palestras-no-primeiro-dia-da-gotex-show", destination: "/noticias/tendencias-inverno-19-e-design-para-estamparia-sao-temas-de-palestras-no-primeiro-dia-da-gotex-show/index.html" },
      { source: "/noticias/terceiro-maior-polo-de-lingerie-do-pais-confirma-parceria-com-a-gotex-show", destination: "/noticias/terceiro-maior-polo-de-lingerie-do-pais-confirma-parceria-com-a-gotex-show/index.html" },
      { source: "/noticias/thermore-freedom-traz-ao-mercado-tecnologia-que-alia-isolante-termico-e-conforto", destination: "/noticias/thermore-freedom-traz-ao-mercado-tecnologia-que-alia-isolante-termico-e-conforto/index.html" },
      { source: "/noticias/thermore-traz-tecnologia-italiana-de-isolamento-termico-para-o-mercado-textil-na-gotex-show-2016", destination: "/noticias/thermore-traz-tecnologia-italiana-de-isolamento-termico-para-o-mercado-textil-na-gotex-show-2016/index.html" },
      { source: "/noticias/tres-visitantes-sao-sorteados-com-ipads-mini", destination: "/noticias/tres-visitantes-sao-sorteados-com-ipads-mini/index.html" },
      { source: "/noticias/vencedora-da-3a-edicao-do-concurso-novos-designers-brasil-realiza-viagem-de-pesquisa-de-moda-na-china", destination: "/noticias/vencedora-da-3a-edicao-do-concurso-novos-designers-brasil-realiza-viagem-de-pesquisa-de-moda-na-china/index.html" },
      { source: "/noticias/vendas-online-tem-sido-principal-ferramenta-para-minimizar-impactos-no-varejo", destination: "/noticias/vendas-online-tem-sido-principal-ferramenta-para-minimizar-impactos-no-varejo/index.html" },
      { source: "/noticias/vice-presidente-da-associacao-textil-da-china-da-as-boas-vindas-ao-publico-da-go-tex-show", destination: "/noticias/vice-presidente-da-associacao-textil-da-china-da-as-boas-vindas-ao-publico-da-go-tex-show/index.html" },
      { source: "/noticias/visita-a-colombia-em-busca-de-maior-conhecimento-e-aproximacao-com-o-mercado", destination: "/noticias/visita-a-colombia-em-busca-de-maior-conhecimento-e-aproximacao-com-o-mercado/index.html" },
      { source: "/noticias/wgsn-preview-inverno-2018", destination: "/noticias/wgsn-preview-inverno-2018/index.html" },
      { source: "/noticias/zhejiang-international-trade-confirma-participacao-e-patrocinio-na-gotex-show-2024", destination: "/noticias/zhejiang-international-trade-confirma-participacao-e-patrocinio-na-gotex-show-2024/index.html" },
    ];
  },
};

export default withPayload(nextConfig);
